### ISSUE TITLE
Specfal.teleport

### ISSUE THREAD

**Issue by bence0726** [bence0726/projlab2#12]
Átírtam ezt a függvényt teljesen, teljesen rossznak tűnt a te megoldásod. Nézd meg pls hogy szerinted is jó-e.

**Comment by guitarrespieler** [comment]
Legközelebb ne töröld ki pls a kódot, csak kommentezd ki, ha nem jó. Elkezdtem írni a választ a kérdésedre, de közben rájöttem, hogy mi volt vele a probléma. A portál irányvektorát helyvektornak kezeltem. Így elvileg jó lesz.
