### ISSUE TITLE
Moveable.move

### ISSUE THREAD

**Issue by bence0726** [bence0726/projlab2#8]
Írtam bele kommentet. 2-t is egyet elejere , másikat legvégére

Továbbá. Ez nem lenne jobb a karakterbe mert egyik leszármazott sem használja ezt az implementáciot. Lényegében se a golyó se a replikátor se a Doboz nem így mozog....

**Comment by guitarrespieler** [comment]
Doboz használja, úgyhogy ott hagytam. A kommentezett részek jók, javítottam.
